### ISSUE TITLE
It might be due to the wrong patches being used.

### ISSUE THREAD

**Issue by plamenko** [positlabs/spark-convolve-test#1]
After sampling a texture, the result is just a color. I believe you can achieve what you want by using Function (Vector2 type) patch instead of Vertex Attribute (Texture Coordinates) patch, and Composition patch instead of Texture Sampler patch.

That way you don't sample the texture at some fixed coordinates which would leave it a color forever, but rather transform the texture which still leaves it a texture.

**Comment by positlabs** [comment]
Moving this here from the FB thread
>Let's say you have a texture which maps some uv coordinates to some rgba color. You can think of that texture as a function from vec2 (uv coords) to vec4 (rgba color).
When you sample that texture at some particular coordinates you'll get some particular color and that's it. This color is no longer a texture.
Now about Function and Composition. Function patch just provides an identity function. E.g. f(uv) = uv. If you add some value (let's call it offset) to that function, the result is another function which behaves as g(uv) = uv + offset.
Likewise, composition just composes two functions. So if we have a texture(uv) and g(uv), their composition is going to be texture(g(uv)). Which in this example is the same as texture(uv + offset). Now this result is a texture and not a color which is useful in case it needs to be transformed and/or sampled later on.

**Comment by positlabs** [comment]
Got it working thanks to your suggestions! Thank you!
